### ISSUE TITLE
Parler project not listed?

### ISSUE THREAD

**Issue by ChadJessup** [ArchiveTeam/parler-grab#2]
Hi there, first time using the warrior system.
I'm using the docker image for parler-grab, but when I go to localhost:8001, Parler is not a project listed.

Is there a step I'm missing?

**Comment by Leko1933** [comment]
its script only, if you have docker setup already its super easy: 

`docker run --detach --name "parler-grab" --restart always atdr.meo.ws/archiveteam/parler-grab:latest --concurrent 20 NICKNAME`

`docker container run -d --restart=unless-stopped --name=watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -i 10 --cleanup`

**Comment by Leko1933** [comment]
The irc channel is where all the latest info is: https://webirc.hackint.org/#irc://irc.hackint.org/#neparlepas

**Comment by ChadJessup** [comment]
Thanks! Closing this out.
